### ISSUE TITLE
Spanish translation -Help needed-

### ISSUE THREAD

**Issue by DogenTM** [Silous888/paranormasight_patcher#1]
Hi! I’m very interested in translating Paranormasight into Spanish language. Any chance you could help me with this? I lack the technical knowledge so I would need help to just extract the texts and injecting them back to the game. My guess is that it should be easy to replace an existing language, like English. Any help would be really appreciated, and thanks in advance for your time :) Please, reach back to me if you want ^^

**Comment by Silous888** [comment]
There is already a Spanish team working on it. We have already send what they need to translate the game (the tool to hack the game has been made by a chinese team).
I don't know how the spanish translation is going. Our contact is roli300. The team is probably TranScene or NAIX Translations. Roli300 worked on Zero Escape (TranScene) and on AI: The Somnium Files (NAIX).
The best for you is probably to contact directly roli300.
His discord is "roli300", his steam too.

**Comment by DogenTM** [comment]
Thanks, man. I appreciate the info! I'm trying to reach to him :) 

Be safe and I wish all the best to you ;)
